# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20c8dc64481b31eb50b4a9e46fc937e65daf6c5ca51d0143b591590cce8c85bfef20734acccc9bfe5ee8e306a84646e2bf699b6559e5f70baab84a531442b8f5

test:
  secret_key_base: 2ab0534ff92b5d57528e438d076dd1661b97d60bea2c30e99891b616c69c370c3ddf2b9f6046e8bfe50eaf9c48399a97da0e0e09085e187fa0b7a00862198a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
